// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Response struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f139a3799a86a974, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "protobuf.Request")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() {
	proto.RegisterFile("math.proto", fileDescriptor_f139a3799a86a974)
}

var fileDescriptor_f139a3799a86a974 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcc, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x80, 0x61, 0xac, 0x42, 0xa9, 0x6e, 0x02, 0x0f, 0x08, 0xc1, 0x82, 0x3c, 0x75, 0xb1, 0x83,
	0xca, 0xc6, 0x06, 0xcc, 0x5d, 0x32, 0xb2, 0x5d, 0xc2, 0x61, 0x5b, 0x8a, 0x3f, 0xb0, 0xcf, 0x52,
	0x7f, 0x3e, 0x22, 0x09, 0x52, 0xa7, 0xf7, 0xee, 0x74, 0x7a, 0x00, 0x02, 0xb2, 0x33, 0xb9, 0x24,
	0x4e, 0x72, 0x37, 0x67, 0x68, 0xdf, 0xea, 0x11, 0xae, 0x7b, 0xfa, 0x69, 0x54, 0x59, 0xde, 0xc0,
	0x26, 0xb6, 0x70, 0x2f, 0x9e, 0xc4, 0xfe, 0xaa, 0xff, 0x1b, 0x95, 0x82, 0x5d, 0x4f, 0x35, 0xa7,
	0x58, 0x49, 0xde, 0xc1, 0xb6, 0x50, 0x6d, 0x13, 0xaf, 0x0f, 0xeb, 0x76, 0x78, 0x85, 0xcb, 0x23,
	0xb2, 0x93, 0x07, 0xd8, 0x1c, 0xf1, 0x24, 0x6f, 0xcd, 0x3f, 0x6d, 0x56, 0xf7, 0x41, 0x9e, 0x9f,
	0x16, 0x4d, 0x5d, 0xec, 0xc5, 0xb3, 0x78, 0xff, 0xf8, 0x7c, 0xb3, 0x9e, 0x5d, 0x1b, 0xcc, 0x98,
	0x42, 0x97, 0xd1, 0x61, 0xf4, 0xd1, 0x77, 0x36, 0x69, 0x5b, 0xf2, 0xa8, 0x07, 0xff, 0xe5, 0x0b,
	0x8d, 0xec, 0x53, 0xc4, 0x49, 0x57, 0x2e, 0x84, 0xc1, 0x47, 0xab, 0xe9, 0x84, 0x21, 0x4f, 0xd4,
	0x2d, 0xec, 0x76, 0xce, 0xcb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xdf, 0x6a, 0x78, 0xe0,
	0x00, 0x00, 0x00,
}
